---
- name: Apply changes on Target Host from Dc to DR
  hosts: all
  gather_facts: no
  vars:
    repo_url: "git@github.com:navneet-rathi/sample.git"
    dest_path: "/tmp/sample"
    commit_msg: "Update replica count from 0 to 1"
    search_string: 'replicas:\s*0'
    replace_string: 'replicas: 1'
  tasks:              
    - name: Try to list namespaces
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
      register: microshift_check

    - name: Report validation result
      debug:
        msg: "Microshift cluster is accessible. Found {{ microshift_check.resources | length }} namespaces."

    - name: Fail if Kubernetes cluster is not accessible
      fail:
        msg: "microshift cluster is NOT accessible!"
      when: microshift_check.failed is defined and microshift_check.failed        

   # - name: make sure git is installed
   #   ansible.builtin.dnf:
   #     name: git
   #     state: latest

### to make changes in git repo #####
    - name: Clone Git repository with SSH key
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_path }}"
        version: main
        accept_hostkey: yes
        #key_file: "~/.ssh/id_rsa"
        update: yes
  #      delegate_to: localhost  

    - name: Find all YAML and manifest files
      ansible.builtin.find:
        paths: "{{ dest_path }}"
        patterns: "*.yaml,*.yml"
        recurse: yes
      register: yaml_files

    - name: Replace replicas count in all matched files
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "{{ search_string }}"
        replace: "{{ replace_string }}"
      loop: "{{ yaml_files.files }}"

    - name: Configure Git username
      ansible.builtin.command: git config user.name "ansible-bot"
      args:
        chdir: "{{ dest_path }}"
#      delegate_to: localhost
      
    - name: Configure Git email
      ansible.builtin.command: git config user.email "nrathi@redhat.com"
      args:
        chdir: "{{ dest_path }}"
#      delegate_to: localhost  
      
    - name: Stage the modified file
      ansible.builtin.command: git add .
      args:
        chdir: "{{ dest_path }}"

    - name: Commit the changes
      ansible.builtin.command: git commit -m "{{ commit_msg }}"
      args:
        chdir: "{{ dest_path }}"
      register: commit_result
      ignore_errors: true
      #failed_when: commit_result.rc != 0 and "'nothing to commit'" not in commit_result.stderr

    - name: Push changes back to Git repo
      ansible.builtin.command: git push origin main
      args:
        chdir: "{{ dest_path }}"
      ignore_errors: true  
      when: commit_result.rc == 0    
