apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default 
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: example-container
        image: nginx:stable-perl
