apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment1
spec:
  replicas: 0
  selector:
    matchLabels:
      app: example1
  template:
    metadata:
      labels:
        app: example1
    spec:
      containers:
      - name: example-container1
        image: example-image1
        ports:
        - containerPort: 8080