- name: Clone, update replica, and push back to repo
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure dos2unix is installed
      ansible.builtin.command: rpm --version

    - name: Convert file to Unix line endings
      ansible.builtin.command: dos2unix deployment.yml